"""LLMwiki backend: wiki-style markdown pages + INDEX, zero infra.

Best for: IDE agents that navigate/grep files directly (Copilot, OpenCode).
Generates `kb/wiki/` from the canonical graph; queries read the generated files.
"""

from __future__ import annotations

import csv
from pathlib import Path

from . import KBBackend
from .graph import Graph, Node, build_graph, graph_stats


def generate_wiki(g: Graph, out_dir: Path) -> None:
    """Generate wiki pages, INDEX.md, and edges.csv from the graph."""
    pages = out_dir / "pages"
    pages.mkdir(parents=True, exist_ok=True)

    # edges.csv — machine-readable edge list
    with (out_dir / "edges.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["src", "dst", "kind"])
        for e in g.edges:
            w.writerow([e.src, e.dst, e.kind])

    # per-node pages with wiki-links to outgoing edges
    out_edges: dict[str, list[tuple[str, str]]] = {}
    for e in g.edges:
        out_edges.setdefault(e.src, []).append((e.dst, e.kind))

    for node in g.nodes.values():
        links = out_edges.get(node.id, [])
        lines = [f"# {node.id}", ""]
        if node.title:
            lines += [f"**{node.title}**", ""]
        if node.content:
            lines += [node.content, ""]
        if links:
            lines += ["## Links", ""]
            for dst, kind in links:
                lines.append(f"- {kind}: [[{dst}]]")
            lines.append("")
        (pages / f"{node.id}.md").write_text("\n".join(lines), encoding="utf-8")

    # INDEX.md — table of all nodes
    lines = [
        "# EU AI Act knowledge wiki",
        "",
        "Generated by `kb/llmwiki_kb.py`. Navigate via pages/ or grep.",
        "",
        "| Node | Type | Title |",
        "|------|------|-------|",
    ]
    for node in sorted(g.nodes.values(), key=lambda n: (n.type, n.id)):
        lines.append(f"| [[{node.id}]] | {node.type} | {node.title[:60]} |")
    lines += ["", f"Edges: {len(g.edges)} (see `edges.csv`)", ""]
    (out_dir / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")


class LLMwikiKB(KBBackend):
    """Query the generated wiki. Call `generate()` first (or use the CLI)."""

    def __init__(self, corpus_dir: Path, wiki_dir: Path | None = None):
        self.wiki_dir = wiki_dir or Path("kb/wiki")
        if not (self.wiki_dir / "INDEX.md").exists():
            g = build_graph(corpus_dir)
            generate_wiki(g, self.wiki_dir)
        self.graph_data: Graph | None = None
        self._load()

    def generate(self, corpus_dir: Path) -> None:
        generate_wiki(build_graph(corpus_dir), self.wiki_dir)
        self._load()

    def _load(self) -> None:
        self.pages: dict[str, str] = {}
        for path in (self.wiki_dir / "pages").glob("*.md"):
            self.pages[path.stem] = path.read_text(encoding="utf-8")
        self.edges: list[tuple[str, str, str]] = []
        with (self.wiki_dir / "edges.csv").open() as f:
            for row in csv.DictReader(f):
                self.edges.append((row["src"], row["dst"], row["kind"]))

    def get_unit(self, unit_id: str) -> Node | None:
        text = self.pages.get(unit_id)
        if text is None:
            return None
        lines = text.splitlines()
        title = lines[0].lstrip("# ").strip() if lines else unit_id
        return Node(id=unit_id, type="", title=title, content=text)

    def references(self, unit_id: str) -> list[str]:
        refs = {dst for src, dst, kind in self.edges if src == unit_id and kind == "REFERENCES"}
        return sorted(refs)

    def obligations_for(self, actor_id: str) -> list[Node]:
        results = []
        for src, dst, kind in self.edges:
            if dst == actor_id and kind == "IMPOSES_ON":
                node = self.get_unit(src)
                if node:
                    results.append(node)
        return results

    def path(self, src: str, dst: str) -> list[str]:
        # BFS over the edge list
        adj: dict[str, list[str]] = {}
        for s, d, _k in self.edges:
            adj.setdefault(s, []).append(d)
        from collections import deque

        queue, seen = deque([[src]]), {src}
        while queue:
            p = queue.popleft()
            if p[-1] == dst:
                return p
            for nxt in adj.get(p[-1], []):
                if nxt not in seen:
                    seen.add(nxt)
                    queue.append(p + [nxt])
        return []

    def search(self, query: str) -> list[str]:
        q = query.lower()
        return [nid for nid, text in self.pages.items() if q in text.lower()]

    def stats(self) -> dict[str, int]:
        stats = {"pages": len(self.pages), "EDGES": len(self.edges)}
        return stats
